wip

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,22 +1,35 @@
-FROM ubuntu:24.04
+ARG VARIANT="noble"
+FROM buildpack-deps:${VARIANT}-curl
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV PYTHONUNBUFFERED=1
+LABEL dev.containers.features="common"
 
-# System Dependencies
-RUN apt-get update && apt-get install -y --no-install-recommends \
-    python3 \
-    python3-venv \
-    python3-pip \
-    curl \
-    jq \
-    git \
-    uuid-runtime \
-    openssh-client \
-    ca-certificates \
- && rm -rf /var/lib/apt/lists/*
+ARG VARIANT
+RUN if [ "$VARIANT" = "noble" ]; then \
+        if id "ubuntu" &>/dev/null; then \
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        else \
+            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        fi; \
+    fi
 
-WORKDIR /workspace
+# [Optional] Uncomment this section to install additional OS packages.
+# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
+#     && apt-get -y install --no-install-recommends <your-package-list-here>
+
+# Local fix for issue with timezone data at 'buildpack-deps'. Ref# https://github.com/devcontainers/images/issues/1709
+RUN apt-get update \
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -y reinstall --no-install-recommends tzdata \
+                                                    python3 \
+                                                    python3-venv \
+                                                    python3-pip \
+                                                    curl \
+                                                    jq \
+                                                    git \
+                                                    uuid-runtime \
+                                                    openssh-client \
+                                                    ca-certificates \    
+    && rm -rf /var/lib/apt/lists/*
 
 # -------------------------
 # Jupyter Base
@@ -26,9 +39,6 @@ RUN python3 -m venv /opt/jupyter \
  && /opt/jupyter/bin/pip install jupyterlab ipykernel \
  && /opt/jupyter/bin/python -m ipykernel install \
       --sys-prefix --name=jupyter --display-name="Python (jupyter)"
-    
-# Mount for docker-in-docker 
-VOLUME [ "/var/lib/docker" ]    
 
 # -------------------------
 # kind
@@ -36,7 +46,7 @@ VOLUME [ "/var/lib/docker" ]
 RUN curl -Lo kind "https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64" \
     && chmod +x kind \
     && mv kind /usr/local/bin/
-    
-RUN curl -L https://github.com/mc-b/duk/archive/refs/heads/master.tar.gz | tar xz --strip-components=3 duk-master/data/jupyter --exclude='*/'
-
+        
+# Mount for docker-in-docker 
+VOLUME [ "/var/lib/docker" ]    
     
